export const ALL_BILLINGS_REQUEST = 'ALL_BILLINGS_REQUEST';
export const ALL_BILLINGS_SUCCESS = 'ALL_BILLINGS_SUCCESS';
export const ALL_BILLINGS_FAIL = 'ALL_BILLINGS_FAIL';

export const NEW_BILLING_REQUEST = 'NEW_BILLING_REQUEST';
export const NEW_BILLING_SUCCESS = 'NEW_BILLING_SUCCESS';
export const NEW_BILLING_RESET = 'NEW_BILLING_RESET';
export const NEW_BILLING_FAIL = 'NEW_BILLING_FAIL';

export const DELETE_BILLING_REQUEST = 'DELETE_BILLING_REQUEST';
export const DELETE_BILLING_SUCCESS = 'DELETE_BILLING_SUCCESS';
export const DELETE_BILLING_RESET = 'DELETE_BILLING_RESET';
export const DELETE_BILLING_FAIL = 'DELETE_BILLING_FAIL';

export const UPDATE_BILLING_REQUEST = 'UPDATE_BILLING_REQUEST';
export const UPDATE_BILLING_SUCCESS = 'UPDATE_BILLING_SUCCESS';
export const UPDATE_BILLING_RESET = 'UPDATE_BILLING_RESET';
export const UPDATE_BILLING_FAIL = 'UPDATE_BILLING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
